### PR TITLE
alloted teachers for the sub are returned when calling the sub api

### PR DESCRIPTION
**Pull request by RoguedBear**
also i freakin hate mongodb 😤😤

### CODE REVIEW

**Comment by RoguedBear** [comment]
the teachers object is also returned, but seperately in `teachersObj` key. run the api on your end one time to see what is benig returned in what format

**Comment by RoguedBear** [comment]
```json
[{"_id":"635ae42c952fad792c74b8a9","id":"CBCA101","Programme":"BCA","__v":0,"choice1":[3],"choice2":[1,4],"choice3":[5],"isAssigned":false,"lectureBatches":1,"name":"Digital Design and Computer Organization","originalStructure":{"L":2,"T":0,"P":2},"totalLecture":2,"totalPractical":6,"totalTutorial":0,"tutLabBatches":3,"allotedTeachers":[{"teacher":"635ae42c952fad792c74b8ad","lectureHrs":1,"tutorialHrs":1,"practicalHrs":1,"_id":"635d57fa49a913bdeff15f38"}],"teachObj":[{"_id":"635ae42c952fad792c74b8ad","id":1,"__v":0,"choice1":{"Subject":"BBCA101","L":0,"T":0,"P":0},"choice2":{"Subject":"BBCA102","L":0,"T":0,"P":0},"choice3":{"Subject":"BBCA103","L":0,"T":0,"P":0},"contact":"8383748734","currentLoad":0,"email":"John Doe@gmail.com","isAssigned":false,"isAvailable":true,"maxLoad":14,"name":"John Doe","subjects":[{"subjectId":"BBCA101","L":0,"T":0,"P":0,"prefOrder":1,"_id":"63680aea15aa32e69567676b"},{"subjectId":"BBCA102","L":0,"T":0,"P":0,"prefOrder":2,"_id":"63680aea15aa32e69567676c"},{"subjectId":"BBCA103","L":0,"T":0,"P":0,"prefOrder":3,"_id":"63680aea15aa32e69567676d"}]}]},{"_id":"635ae42c952fad792c74b8aa","id":"CSET101","Programme":"BTECH","__v":0,"choice1":[1,2],"choice2":[5],"choice3":[6,7],"isAssigned":false,"lectureBatches":8,"name":"Computational Thinking and Programming","originalStructure":{"L":2,"T":1,"P":4},"totalLecture":16,"totalPractical":120,"totalTutorial":30,"tutLabBatches":30,"allotedTeachers":[{"teacher":"635ae42c952fad792c74b8ad","lectureHrs":4,"tutorialHrs":3,"practicalHrs":2,"_id":"635d57fa49a913bdeff15f36"},{"teacher":"635ae42c952fad792c74b8ae","lectureHrs":3,"tutorialHrs":3,"practicalHrs":3,"_id":"635d57fa49a913bdeff15f36"}],"teachObj":[{"_id":"635ae42c952fad792c74b8ad","id":1,"__v":0,"choice1":{"Subject":"BBCA101","L":0,"T":0,"P":0},"choice2":{"Subject":"BBCA102","L":0,"T":0,"P":0},"choice3":{"Subject":"BBCA103","L":0,"T":0,"P":0},"contact":"8383748734","currentLoad":0,"email":"John Doe@gmail.com","isAssigned":false,"isAvailable":true,"maxLoad":14,"name":"John Doe","subjects":[{"subjectId":"BBCA101","L":0,"T":0,"P":0,"prefOrder":1,"_id":"63680aea15aa32e69567676b"},{"subjectId":"BBCA102","L":0,"T":0,"P":0,"prefOrder":2,"_id":"63680aea15aa32e69567676c"},{"subjectId":"BBCA103","L":0,"T":0,"P":0,"prefOrder":3,"_id":"63680aea15aa32e69567676d"}]},{"_id":"635ae42c952fad792c74b8ae","id":5,"__v":0,"choice1":{"Subject":"BBCA101","L":0,"T":0,"P":0},"choice2":{"Subject":"BBCA102","L":0,"T":0,"P":0},"choice3":{"Subject":"BBCA103","L":0,"T":0,"P":0},"contact":"8383748734","currentLoad":0,"email":"pranay@gmail.com","isAssigned":false,"isAvailable":true,"maxLoad":14,"name":"Pranay","subjects":[{"subjectId":"BBCA101","L":0,"T":0,"P":0,"prefOrder":1,"_id":"63680aea15aa32e69567677b"},{"subjectId":"BBCA102","L":0,"T":0,"P":0,"prefOrder":2,"_id":"63680aea15aa32e69567677c"},{"subjectId":"BBCA103","L":0,"T":0,"P":0,"prefOrder":3,"_id":"63680aea15aa32e69567677d"}]}]},{"_id":"635ae42c952fad792c74b8ab","id":"CBCA102","Programme":"BCA","__v":0,"choice1":[4,5],"choice2":[2,8],"choice3":[1],"isAssigned":true,"lectureBatches":1,"name":"Computational Thinking with Python","originalStructure":{"L":2,"T":1,"P":4},"totalLecture":2,"totalPractical":12,"totalTutorial":3,"tutLabBatches":3,"allotedTeachers":[{"teacher":"635ae42c952fad792c74b8ad","lectureHrs":1,"tutorialHrs":0,"practicalHrs":0,"_id":"635f832b5fdb66ef6c8c488a"}],"teachObj":[{"_id":"635ae42c952fad792c74b8ad","id":1,"__v":0,"choice1":{"Subject":"BBCA101","L":0,"T":0,"P":0},"choice2":{"Subject":"BBCA102","L":0,"T":0,"P":0},"choice3":{"Subject":"BBCA103","L":0,"T":0,"P":0},"contact":"8383748734","currentLoad":0,"email":"John Doe@gmail.com","isAssigned":false,"isAvailable":true,"maxLoad":14,"name":"John Doe","subjects":[{"subjectId":"BBCA101","L":0,"T":0,"P":0,"prefOrder":1,"_id":"63680aea15aa32e69567676b"},{"subjectId":"BBCA102","L":0,"T":0,"P":0,"prefOrder":2,"_id":"63680aea15aa32e69567676c"},{"subjectId":"BBCA103","L":0,"T":0,"P":0,"prefOrder":3,"_id":"63680aea15aa32e69567676d"}]}]}]
```

**Review by Chirag4904 — CHANGES_REQUESTED** [review]
So there's a problem in this that now if we call the subjects api then it is showing only the subjects which are present in allotment collection and not showing the subjects which are not in allotment collection.

**Comment by RoguedBear** [comment]
I'll give it a look and fix it. 
thanks for the update

**Pull request merged**
